### ISSUE TITLE
[irods4 installation script] lsb-release issue ?

### ISSUE THREAD

**Issue by dbenaben** [mesocentre-mcia/mcia-irods-client-install#14]
Under RedHat OS (CentOS, RockyLinux, ..), `lsb-release` doesn't exist which could be error-prone.
Under ubuntu, it requires `lsb-release` tool (or you will donwnload rpm packages) 

https://github.com/mesocentre-mcia/mcia-irods-client-install/blob/f484823ee0fd39021f0cf470a4fd13797691f478/icommands-install.sh#L9

```
./icommands-install.sh: line 9: lsb_release: command not found
```

Maybe use another method ?

**Comment by pigay** [comment]
these packages seem to be installed by default, at least with standard distro installs...

Did you encounter the error in some container environment?

**Comment by dbenaben** [comment]
Yes, you're right, I only test in container environment. But I didn't find lsb_release command on CentOS in real environment. `/etc/os-release` seems more generic. But it's probably a detail...

**Comment by pigay** [comment]
In CentOS, it's in the redhat-lsb-core RPM. Same for Rocky

**Comment by dbenaben** [comment]
Ok. On the other hand it's not installed by default on CentOS (I think). But we can close the ticket if it seems not relevant.
